Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2020-08, with the labels that each got.

#35 Release v6.2.0 images
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S

#36 updated the docker image configmap and pom for latest changes to supp…
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  pom.xml
Labels: approved, size/S

#37 ReRelease of 6.2.0
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/XS

#38 ENG-1020 upgrading keycloak and some minor template tweaks for Poste
  charts/entando-k8s-controller-coordinator/README.md
  charts/entando-k8s-controller-coordinator/templates/ca-cert-secret.yaml
  charts/entando-k8s-controller-coordinator/templates/deployment.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/k8s-service-serviceaccount.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-serviceaccount.yaml
  charts/entando-k8s-controller-coordinator/templates/plugin-serviceaccount.yaml
  charts/entando-k8s-controller-coordinator/values.yaml
  charts/preview/values.yaml
  src/main/bash/copy-images.sh
  src/main/bash/get-jvm-images.sh
Labels: approved, size/M

#39 ENG-1065 configfurable serviceaccounts
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  pom.xml
Labels: approved, size/S

#40 Eng 1065 configurable serviceaccounts
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/XS
