Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2020-02, with the labels that each got.

#4 Bumped to latest images
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S

#5 Adds a conditional to fix RBAC exceptions on openshift
  charts/entando-k8s-controller-coordinator/templates/operator-role.yaml
Labels: approved, size/XS

#6 Removes the conditional to support minikube
  charts/entando-k8s-controller-coordinator/templates/operator-role.yaml
Labels: approved, size/XS

#7 Added license and updated dependencies
  .gitignore
  .idea/copyright/Entando.xml
  .idea/copyright/profiles_settings.xml
  LICENSE
  charts/entando-k8s-controller-coordinator/templates/deployment.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/values.yaml
  config/owasp-dependency-check-suppression.xml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinator.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoDeploymentPhaseWatcher.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
  src/main/resources/reflection-config.json
  src/test/java/org/entando/kubernetes/controller/coordinator/AbstractControllerCoordinatorTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/ImageVersionPreparation.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorEdgeConditionsTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorMockedTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/DeploymentPhaseWatcherTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/interprocesstests/ControllerCoordinatorIntegratedTest.java
Labels: approved, size/L
