Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2020-11, with the labels that each got.

#52 Eng 1447 improved keycloak config
  charts/entando-k8s-controller-coordinator/templates/ca-cert-secret.yaml
  charts/entando-k8s-controller-coordinator/templates/deployment.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-clusterrole.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-pod-viewer-clusterrolebinding.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-role.yaml
  charts/entando-k8s-controller-coordinator/templates/pod-viewer-clusterrole.yaml
  charts/entando-k8s-controller-coordinator/templates/tls-secret.yaml
  charts/entando-k8s-controller-coordinator/values.yaml
  charts/preview/templates/ca-secret.yaml
  charts/preview/templates/tls-secret.yaml
  pom.xml
  src/main/bash/copy-images.sh
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinator.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorMockedTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/interprocesstests/ControllerCoordinatorIntegratedTest.java
Labels: approved, size/L

#53 Eng 1447 improved keycloak config
  charts/entando-k8s-controller-coordinator/README.md
  charts/entando-k8s-controller-coordinator/templates/deployment.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/values.yaml
  charts/preview/templates/ca-secret.yaml
  charts/preview/templates/tls-secret.yaml
  charts/preview/values.yaml
  src/main/bash/copy-images.sh
Labels: approved, size/M

#54 ENG-1507 changed the default operator mode to strict
  charts/entando-k8s-controller-coordinator/values.yaml
Labels: approved, size/XS

#55 Update docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S

#56 ENG-1534 default serviceaccount can now read pods in namespace deploy…
  charts/entando-k8s-controller-coordinator/templates/default-pod-viewer-rolebinding.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/pod-viewer-role.yaml
  pom.xml
Labels: approved, size/M

#57 ENG-1534 consistently supporting Release.Namespace
  charts/entando-k8s-controller-coordinator/templates/default-pod-viewer-rolebinding.yaml
  charts/entando-k8s-controller-coordinator/templates/plugin-rolebinding.yaml
  charts/entando-k8s-controller-coordinator/templates/pod-viewer-role.yaml
Labels: approved, size/XS
