Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2020-10, with the labels that each got.

#44 ENG-1338 Backport to sprint10 of the fixes for the page token generation
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/XS

#45 Eng 1205 clusterwide scope
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/entando-editor-clusterrole.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-clusterrole.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-clusterrolebinding.yaml
  pom.xml
Labels: approved, size/L

#47 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#48 Update docker-image-info-configmap.yaml for 6.3.0 Sprint11 release
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S

#49 ENG-872 bumped to latest dependencies
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-clusterrole.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-role.yaml
  pom.xml
  src/test/java/org/entando/kubernetes/controller/coordinator/AbstractControllerCoordinatorTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorEdgeConditionsTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorMockedTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/DeploymentPhaseWatcherTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/EntandoOperatorMatcherTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/interprocesstests/ControllerCoordinatorIntegratedTest.java
Labels: approved, size/M

#50 Eng 1329 latest images
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinator.java
  src/test/java/org/entando/kubernetes/controller/coordinator/AbstractControllerCoordinatorTest.java
Labels: approved, size/M

#51 ENG-1329 auto creating view rolebinding for K8S now
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-clusterrole.yaml
  pom.xml
Labels: approved, size/S
