Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2020-06, with the labels that each got.

#26 Eng 562 h2 derby support
  .idea/codeStyles/Project.xml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  config/checkstyle/checkstyle.xml
  config/intellij-java-entando-style.xml
  config/owasp-dependency-check-suppression.xml
  jenkins-x.yml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
  src/test/java/org/entando/kubernetes/controller/coordinator/AbstractControllerCoordinatorTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorMockedTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/interprocesstests/ControllerCoordinatorIntegratedTest.java
Labels: approved, size/XXL

#28 Update image versions for sprint RC
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S

#29 Entando-de-app image update
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/XS

#30 Eng 650 nginx ingress support
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
Labels: approved, size/S

#31 Updates the versions to match v6.2.0 Sprint 4 release candidate
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S
