Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2020-09, with the labels that each got.

#41 Eng 1205 cluster wide deployment
  .idea/runConfigurations/Interprocess.xml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinator.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoOperatorMatcher.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
  src/test/java/org/entando/kubernetes/controller/coordinator/AbstractControllerCoordinatorTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorEdgeConditionsTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorMockedTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/DeploymentPhaseWatcherTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/EntandoOperatorMatcherTest.java
Labels: approved, size/L

#42 ENG-1205 cluster scope
  charts/.gitignore
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/k8s-service-role.yaml
  charts/entando-k8s-controller-coordinator/templates/k8s-service-rolebinding.yaml
  charts/entando-k8s-controller-coordinator/templates/k8s-service-serviceaccount.yaml
  charts/entando-k8s-controller-coordinator/templates/operator-role.yaml
  charts/entando-k8s-controller-coordinator/templates/plugin-role.yaml
  charts/entando-k8s-controller-coordinator/templates/plugin-rolebinding.yaml
  charts/entando-k8s-controller-coordinator/templates/plugin-serviceaccount.yaml
  charts/entando-k8s-controller-coordinator/values.yaml
  jenkins-x.yml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
Labels: approved, size/M

#43 6.2.1-Sprint10-Release Upgrade Component Versions
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
Labels: approved, size/S
