Repository entando-k8s/entando-k8s-controller-coordinator, pull requests merged in 2021-03, with the labels that each got.

#68 ENG-1829 improved resource management
  Dockerfile.jvm
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinatorProperty.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoOperatorMatcher.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorEdgeConditionsTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorMockedTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/interprocesstests/ControllerCoordinatorIntegratedTest.java
Labels: approved, size/L

#69 ENG-1876 removed unnecessary Secret mounts
  Dockerfile.jvm
  README.md
  charts/entando-k8s-controller-coordinator/templates/deployment.yaml
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/values.yaml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinator.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoOperatorMatcher.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoResourceObserver.java
  src/main/java/org/entando/kubernetes/controller/coordinator/TrustStoreSecretRegenerator.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/ControllerCoordinatorEdgeConditionsTest.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/CoordinatorK8SClientDouble.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/SimpleEntandoOperationsDouble.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/SimpleEntandoOperationsRegistryDouble.java
  src/test/java/org/entando/kubernetes/controller/coordinator/inprocesstests/TrustStoreSecretRegeneratorTest.java
Labels: approved, size/L

#71 Update OWNERS
  OWNERS
Labels: approved, size/XS

#70 ENG-1876 fixed some version inconsistencies
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/entando-emtpy-tls-secret.yaml
  src/main/java/org/entando/kubernetes/controller/coordinator/ConfigListener.java
  src/main/java/org/entando/kubernetes/controller/coordinator/DefaultSimpleEntandoOperations.java
  src/main/java/org/entando/kubernetes/controller/coordinator/EntandoControllerCoordinator.java
Labels: approved, size/L

#72 ENG-2062 updated all latest images for release build
  charts/entando-k8s-controller-coordinator/templates/docker-image-info-configmap.yaml
  charts/entando-k8s-controller-coordinator/templates/entando-empty-tls-secret.yaml
  pom.xml
Labels: approved, size/S
